---                                                                                
title: "<p id = \"title1\"> Merchant </p> \n<p id = \"title2\"> Report Card </p> \n"
output:
  html_document:
    css: mystyle.css
params:
  merchant_id : "icicipru"
---


```{r queries, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
mid <- params$merchant_id
source("data.R",local = knitr::knit_global())
#knitr::current_input()


library(ggrepel)
library(lubridate)

# library(ggrepel)
# library(lubridate)
options(tinytex.verbose = FALSE)

```
<div id = "underline_title_heading" >
`r heading_text_1`
</div>

<br><br>

::: {.break-after}
```{r single_stats, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE}

singleStatBox <-
  function(value,
           delta,
           label,
           del_color_check,
           info_content , reverse_vector) {  
    if(label %in% reverse_vector) { 
    if (del_color_check <= 0) {
      
      color_id <- "del_color_green"
      icon <- "↓"
    } else{
      color_id <- "del_color_red"
      icon <- "↑"
    }
      
    }else{
         if (del_color_check > 0) {
      color_id <- "del_color_green"
      icon <- "↑"
    } else{
      color_id <- "del_color_red"
      icon <- "↓"
    }
    }
    element <- 
str_interp(
      '
<div class = "main_box">
<div class = "box_contents">
<div class = "metrics">
<div class = "label-whole"><p class="label" style="color: #0a0a0a;">${label}</p>
 <span class="tool" data-tip= "${info_content}" tabindex="1"><svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24"><path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-.001 5.75c.69 0 1.251.56 1.251 1.25s-.561 1.25-1.251 1.25-1.249-.56-1.249-1.25.559-1.25 1.249-1.25zm2.001 12.25h-4v-1c.484-.179 1-.201 1-.735v-4.467c0-.534-.516-.618-1-.797v-1h3v6.265c0 .535.517.558 1 .735v.999z"/></svg></span>
</div>
<div class = "value">${value}</div>
<div id ="${color_id}" class = "delta">${delta} ${icon}</div>
</div>
</div>
</div>'
    )
    
    return(element)
  }

cardBlock <- function(name, box_1, box_2, box_3, blocks = 3) {
  if (blocks == 3) {
    block <- str_interp('
<div class = "${name}">
${box_1}
${box_2}
${box_3}
</div>
')
  } else if (blocks == 2) {
    block <- str_interp('
<div class = "${name}">
${box_1}
${box_2}
</div>
')
  } else if (blocks == 1) {
    block <- str_interp('
<div class = "${name}">
${box_1}
</div>
')
  }
  
  
  
  return(block)
}

cardView <- function(block1, block2, block3, views = 2) {
  if (views == 3) {
    card <- str_interp('
<div class = "card_view">
${block1}
${block2}
${block3}
</div>')
    
  } else{
    card <- str_interp('
<div class = "card_view">
${block1}
${block2}
</div>')
  }
  
  return(card)
}

labels_payments = c(
  "Overall Successful Orders",
  "Order Success Rate",
  "First Attempt Success Rate",
  "Delayed Order Success Rate",
  "99th % Turn Around Time",
  "Gross GMV",
  "Net GMV"
)

labels_refund = c(
  "Overall Successful Refunds",
  "Refund Success Rate",
  "Pending Refunds",
  "Manual Review Refunds",
  "99th % Turn Around Time",
  "Processed Refund Amount",
  "Conflicted Refunds"
)

info_payments = c(
  "Successful orders in the mentioned time period",
  "Successful orders over total orders iniatiated",
  "Order got successful on the first attempt",
  "Successful orders where a delayed response is received over total orders initiated in the mentioned time period",
  "Time taken for 99% of transactions to become successful",
  "Total order amount processed successfully",
  "Total successful orders amount - Total successful refunds amount"
)

info_refunds = c(
  "Successful refunds in the mentioned time period ",
  "Successful refunds over total refunds initiated",
  "Count of refunds which have been Pending",
  "Count of refunds which require manual intervention",
  "Time taken for 99% of refunds to become successful",
  "Total amount refunded successfully",
  "Conflicted Refunds"
)

boxes_payments <- list()
boxes_refund <- list()

for (i in 1:7) {
  box <-
    singleStatBox(
      payment_vector[i],
      delta_payment_final_vector[i],
      labels_payments[i],
      delta_payment_vector[i],
      info_payments[i],
      payments_reverse_vector
    )
  boxes_payments[[length(boxes_payments) + 1]] <- box
}

for (i in 1:7) {
  box <-
    singleStatBox(
      refund_vector[i],
      delta_refund_final_vector[i],
      labels_refund[i],
      delta_refund_vector[i],
      info_refunds[i],
      refund_reverse_vector
    )
  boxes_refund[[length(boxes_refund) + 1]] <- box
}

p1 <-
  cardBlock("p_block_1",
            box_1 = boxes_payments[1],
            box_2 = boxes_payments[2],
            box_3 = boxes_payments[3])
p2 <-
  cardBlock("p_block_2",
            box_1 = boxes_payments[4],
            box_2 = boxes_payments[5],
            box_3 = boxes_payments[6])
p3 <- cardBlock("p_block_3", box_1 = boxes_payments[7], blocks = 1)

r1 <-
  cardBlock("r_block_1",
            box_1 = boxes_refund[1],
            box_2 = boxes_refund[2],
            box_3 = boxes_refund[3])
r2 <-
  cardBlock("r_block_2",
            box_1 = boxes_refund[4],
            box_2 = boxes_refund[5],
            box_3 = boxes_refund[6])
r3 <- cardBlock("r_block_3", box_1 = boxes_refund[7], blocks = 1)

```

<br><br>
`r heading_text_payments`
`r cardView(p1,p2,p3,views =3 )`
<br><br>
<br><br>
`r heading_text_refunds`
`r cardView(r1,r2,r3,views =3)`
<br><br>
:::

<br><br>
<br><br>
<div id = "performace_heading" >
`r heading_text_product_performance`
</div>

:::{.mr_plots_highchart}
```{r sr_pmt, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(vol_sr_pmt_table)>0) {
  chart_height <- setChartHeight(nrow(vol_sr_pmt_table))
  
  vol_sr_pmt_table <-
    vol_sr_pmt_table %>% rename(
      "Success Rate" = osr,
      "Payment Method Type" = payment_method_type,
      "Volume" = total_orders
    )  %>% arrange(desc(Volume))
  
  
  plot <-
    hchart(
      object = vol_sr_pmt_table,
      type = "bar",
      hcaes(x = `Payment Method Type`, y = `Success Rate`),
      color = "#DCEDC1",
      marginRight = 100
    ) %>%
    hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      ),
      zones =  list(
        list(
          value = min(vol_sr_pmt_table$`Success Rate`) + 1,
          color = '#EA5D5D'
        ),
        list(
          value = max(vol_sr_pmt_table$`Success Rate`),
          color = '#5C9DB9'
        ),
        list(color = '#5AAF3D')
      )
    )) %>% hc_title(text = "Payment Method Type Wise Success Rate", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_size(height = chart_height) %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                                                            labels = list(formatter = JS(
                                                                                                                                                                              "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                                                            )))  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  plot
  return(plot)
}
```

```{r vol_pmt, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(vol_sr_pmt_table) > 0) {
  chart_height <- setChartHeight(nrow(vol_sr_pmt_table))
  
  plot <-
    hchart(
      object = vol_sr_pmt_table,
      type = "bar",
      hcaes(x = `Payment Method Type`, y = `Volume`),
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold')
      ),
      zones =  list(
        list(
          value = min(vol_sr_pmt_table$`Volume`) + 1,
          color = '#EA5D5D'
        ),
        list(
          value = max(vol_sr_pmt_table$`Volume`),
          color = '#5C9DB9'
        ),
        list(color = '#5AAF3D')
      )
    )) %>% hc_title(text = "Payment Method Type Wise Volume", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_size(height = chart_height) %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_yAxis(title = list(margin = 15)) %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  plot
  return(plot)
}

```
:::

:::{.mr_plots_highchart}
```{r sr_pg, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(vol_sr_pg_table) > 0) {
  chart_height <- setChartHeight(nrow(vol_sr_pg_table))
  
  
  vol_sr_pg_table <-
    vol_sr_pg_table %>%  rename(
      "Success Rate" = osr,
      "Payment Gateway" = gateway,
      "Volume" = total_orders
    ) %>%
    arrange(desc(`Volume`))
  
  plot <-
    hchart(
      object = vol_sr_pg_table,
      type = "bar",
      hcaes(x = `Payment Gateway`, y = `Success Rate`),
      marginRight = 100
    ) %>%
    hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      ),
      zones =  list(
        list(
          value = min(vol_sr_pg_table$`Success Rate`) + 1,
          color = '#EA5D5D'
        ),
        list(
          value = max(vol_sr_pg_table$`Success Rate`),
          color = '#5C9DB9'
        ),
        list(color = '#5AAF3D')
      )
    )) %>% hc_title(text = "Payment Gateway Wise Success Rate") %>%  hc_chart(backgroundColor = '#ffffff', className = "pg-sr-chart") %>% hc_size(height = chart_height) %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                                                                      labels = list(formatter = JS(
                                                                                                                                                                                        "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                                                                      ))) %>% hc_xAxis(title = list(margin = 15)) %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  plot
  return(plot)
}

```

```{r vol_pg, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(vol_sr_pg_table) > 0) {
  chart_height <- setChartHeight(nrow(vol_sr_pg_table))
  
  plot <-
    hchart(
      object = vol_sr_pg_table,
      type = "bar",
      hcaes(x = `Payment Gateway`, y = `Volume`),
      color = "#DCEDC1",
      marginRight = 100
    ) %>%
    hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold')
      ),
      zones =  list(
        list(
          value = min(vol_sr_pg_table$`Volume`) + 1,
          color = '#EA5D5D'
        ),
        list(
          value = max(vol_sr_pg_table$`Volume`),
          color = '#5C9DB9'
        ),
        list(color = '#5AAF3D')
      )
    )) %>% hc_title(text = "Payment Gateway Wise Volume", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff', className = "pg-sr-chart") %>% hc_size(height = chart_height) %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_yAxis(title = list(margin = 15)) %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  plot
  return(plot)
}
```
:::


```{r auth_otp_3ds_heading, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
# !is.na(auth_table_2$otp_sr) && !is.na(auth_table_2$threeds_sr) &&
if( (nrow(auth_table_2) > 0 && (auth_table_2$otp_sr > auth_table_2$threeds_sr)) || !is.na(auth_table_2_juspay$threeds_sr) && nrow(auth_table_2_juspay) > 0 && (auth_table_2_juspay$otp_sr > auth_table_2_juspay$threeds_sr))
   {
dotp_text <- text_spec(paste("Native OTP Performance"),
                       "html")

note <- str_interp('<div id = "heading">
${dotp_text}
</div>')

cat(note)
}
```

:::{.mr_plots_highchart}
```{r auth_otp_3ds_1, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}

  if(!is.na(auth_table_2$otp_sr) && !is.na(auth_table_2$threeds_sr) && nrow(auth_table_2) > 0 && (auth_table_2$otp_sr > auth_table_2$threeds_sr)){
  # nrow(auth_table_2) > 0 && auth_table_2$otp_sr > auth_table_2$threeds_sr) {
  tmp <-
    auth_table_2 %>% rename("Native OTP" = otp_sr, "THREE DS" = threeds_sr)
  tmp <- as.data.frame(t(tmp))
  names(tmp) <- c("Success Rate")
  tmp <- slice(tmp, 1:2)
  tmp$`Auth Type` <- row.names(tmp)
  row.names(tmp) <- NULL
  
  plot <-
    hchart(
      object = tmp,
      type = "bar",
      hcaes(x = `Auth Type`, y = `Success Rate`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      )
    )) %>% hc_title(text = "Native OTP Vs 3DS Success Rate", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                  labels = list(formatter = JS(
                                                                                                                                    "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                  ))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  return(plot)
}

```

```{r auth_otp_3ds_2, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
  if(!is.na(auth_table_2$otp_sr) && !is.na(auth_table_2$threeds_sr) && nrow(auth_table_2) > 0 && (auth_table_2$otp_sr > auth_table_2$threeds_sr)){
  tmp <- auth_table_2
  tmp <- as.data.frame(t(tmp))
  names(tmp) <- c("Volume")
  tmp <- slice(tmp, 3:6)
  tmp$`Auth Type` <- row.names(tmp)
  row.names(tmp) <- NULL
  tmp$`Auth Type`[tmp$`Auth Type` == "t_otp_txns"] <- "Native OTP"
  tmp$`Auth Type`[tmp$`Auth Type` == "t_3ds_txns"] <- "THREE DS"
  
  t <-
    tmp[tmp$`Auth Type` == "Native OTP" |
          tmp$`Auth Type` == "THREE DS", ]
  t$`s_vol` <- NULL
  t[t$`Auth Type` == "Native OTP" , "s_vol"] <-
    tmp[tmp$`Auth Type` == "s_otp_txns" , "Volume"]
  t[t$`Auth Type` == "THREE DS" , "s_vol"] <-
    tmp[tmp$`Auth Type` == "s_3ds_txns" , "Volume"]
  
  
  plot <-
    hchart(
      object = t,
      type = "bar",
      hcaes(x = `Auth Type`, y = `Volume`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y  }")
      )
    )) %>% hc_title(text = "Native OTP Vs 3DS Volume", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                            labels = list(formatter = JS("function(){ return '<b>' + this.value}"))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>Total Volume: {point.y}</p><p>Successful Volume : </p><p>{point.s_vol}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  
  return(plot)
}

```
:::

```{r auth_otp_3ds_juspay, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if( !is.na(auth_table_2_juspay$threeds_sr) && nrow(auth_table_2_juspay) > 0 && (auth_table_2_juspay$otp_sr > auth_table_2_juspay$threeds_sr)) {
  tmp <-
    auth_table_2_juspay %>% rename("Juspay Level Native OTP" = otp_sr, "THREE DS" =
                                     threeds_sr)
  tmp <- as.data.frame(t(tmp))
  names(tmp) <- c("Success Rate")
  tmp <- slice(tmp, 1:2)
  tmp$`Auth Type` <- row.names(tmp)
  row.names(tmp) <- NULL
  
  plot <-
    hchart(
      object = tmp,
      type = "bar",
      hcaes(x = `Auth Type`, y = `Success Rate`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      )
    )) %>% hc_title(text = "Juspay Level Native OTP Vs Merchant 3DS Success Rate", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                                        labels = list(formatter = JS(
                                                                                                                                                          "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                                        ))) %>% hc_size(width = 1160, height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  return(plot)
}

```


```{r auth_3ds_note, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
 if(!is.na(auth_table_2$otp_sr) && !is.na(auth_table_2$threeds_sr) && nrow(auth_table_2) > 0 && (auth_table_2$otp_sr > auth_table_2$threeds_sr)){

  auth_text <- text_spec(
    paste(
      "Note: Comparison of Card Native OTP transactions to Card 3DS transactions. Card Native OTP is powered by  Juspay SDK"
    ),
    "html",
    color = "#666F7D",
    font_size = 14,
    extra_css = note_css
  )
} else if (nrow(auth_table_2_juspay) > 0) {
  auth_text <- text_spec(
    paste(
      "Note: Comparison of Juspay level Card Native OTP transactions SR to merchant level Card 3DS transactions. Card Native OTP is powered by Juspay SDK"
    ),
    "html",
    color = "#666F7D",
    font_size = 14,
    extra_css = note_css
  )
} else{
  auth_text <- ""
}

note <- str_interp('<div class = "text_note ">
${auth_text}
<br><br>
</div>')

cat(note)

```

```{r gpay_heading, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}


if (nrow(gpay_table) > 0 ) {
wallet_sr <- gpay_table %>% filter(payment_type ==  'WALLET') %>% .$SR
upi_sr <- gpay_table %>% filter(payment_type ==  'UPI') %>% .$SR
if (nrow(gpay_table) > 0 & wallet_sr > upi_sr) {
  gpay_text <- text_spec(paste("GPAY DEEP INTENT PERFORMANCE"),
                       "html")

note <- str_interp('<div id = "heading">
${gpay_text}
</div>')

  cat(note)
}

}

```

:::{.mr_plots_highchart}
```{r gpay_sdk_vs_upi_sr, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}

if(nrow(gpay_table)>0) {
wallet_sr <- gpay_table %>% filter(payment_type ==  'WALLET') %>% .$SR
upi_sr <- gpay_table %>% filter(payment_type ==  'UPI') %>% .$SR
if ( wallet_sr >upi_sr) {
      gpay_table <-
    gpay_table %>% drop_na() %>% arrange(desc(SR)) %>% rename("Success Rate" = SR, "Intent" = payment_type)

  gpay_table$Intent[gpay_table$Intent == "UPI"] <- "Normal Intent"
  gpay_table$Intent[gpay_table$Intent == "WALLET"] <- "Deep Intent"

  plot <-
    hchart(
      object = gpay_table,
      type = "bar",
      hcaes(x = Intent, y = `Success Rate`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      )
    )) %>% hc_title(text = "GPay Deep Intent Vs GPay Normal Intent Success Rate") %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                          labels = list(formatter = JS(
                                                                                                                                            "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                          ))) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>')  %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  plot
  return(plot)
}
  }

```

```{r gpay_sdk_vs_upi_vol, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(gpay_table)>0) {
  wallet_sr <- gpay_table %>% filter(payment_type ==  'WALLET') %>% .$SR
  upi_sr <- gpay_table %>% filter(payment_type ==  'UPI') %>% .$SR
  if (wallet_sr >upi_sr) {
  plot <-
    hchart(
      object = gpay_table,
      type = "bar",
      hcaes(x = Intent, y = volume),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y }")
      )
    )) %>% hc_title(text = "GPay Deep Intent Vs GPay Normal Intent Volume") %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                    labels = list(formatter = JS("function(){ return '<b>' + this.value }"))) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>')  %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  plot
  return(plot)
  }
  }
```
:::
```{r gpay_sdk_vs_upi_sr_juspay, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
# if(nrow(gpay_table_juspay)>0) {
#   gpay_table_juspay <-
#     gpay_table_juspay %>% drop_na() %>% arrange(desc(SR)) %>% rename("Success Rate" = SR, "Intent" = payment_type)
# 
#   gpay_table_juspay$Intent[gpay_table_juspay$Intent == "UPI"] <-
#     "Normal Intent"
#   gpay_table_juspay$Intent[gpay_table_juspay$Intent == "WALLET"] <-
#     "Deep Intent"
#   
#   plot <-
#     hchart(
#       object = gpay_table_juspay,
#       type = "bar",
#       hcaes(x = Intent, y = `Success Rate`),
#       color = "#5C9DB9",
#       marginRight = 100
#     ) %>% hc_plotOptions(bar = list(
#       pointWidth = 34,
#       dataLabels = list(
#         enabled = T,
#         inside = T,
#         crop = F,
#         color = '#222222',
#         style = list(textOutline = 0, fontWeight = 'bold'),
#         formatter = JS("function(){ return '<b>' + this.y +'%' }")
#       )
#     )) %>% hc_title(text = "GPay Deep Intent Vs GPay Normal Intent Success Rate") %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
#                                                                                                                                           labels = list(formatter = JS(
#                                                                                                                                             "function(){ return '<b>' + this.value +'%' }"
#                                                                                                                                           ))) %>% hc_size(width = 1160, height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>')  %>% hc_xAxis(title = list(margin = 15)) %>%
#     hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
#   plot
#   return(plot)
# }
```

```{r gpay_note, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if (nrow(gpay_table) > 0) {
  gpay_text_note <- ""
  wallet_sr <- gpay_table %>% filter(payment_type ==  'WALLET') %>% .$SR
  upi_sr <- gpay_table %>% filter(payment_type ==  'UPI') %>% .$SR
  if (nrow(gpay_table) > 0 &&  wallet_sr > upi_sr ) {

    gpay_text_note <- text_spec(
      paste(
        "Note: Comparison of Juspay level Gpay UPI Deep Intent Transactions SR to Merchant level Gpay UPI Intent transactions. Gpay UPI Deep Intent is powered by Gpay SDK on Juspay"
      ),
      "html",
      color = "#666F7D",
      font_size = 14,
      extra_css = note_css
    )
  }
  
  note <- str_interp('<div class = "text_note">
${gpay_text_note}
<br><br>
</div>')
cat(note)
}


```

```{r mandates_heading, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(!is.na(mandate_vs_normal$mandate_sr) && !is.na(mandate_vs_normal$order_sr) && nrow(mandate_vs_normal) > 0 & mandate_vs_normal$mandate_sr > mandate_vs_normal$order_sr) {
mandate_text <- text_spec(paste("Mandate Vs Non Mandates Performance"),
                       "html")
}
note <- str_interp('<div id = "heading">
${mandate_text}
</div>')
cat(note)
```

:::{.mr_plots_highchart}
```{r mandates_table_sr, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(!is.na(mandate_vs_normal$mandate_sr) && !is.na(mandate_vs_normal$order_sr) && nrow(mandate_vs_normal) > 0 & mandate_vs_normal$mandate_sr > mandate_vs_normal$order_sr) {
  tmp <-
    mandate_vs_normal %>% rename("Mandates" = mandate_sr, "Non Mandates" =order_sr )
  tmp <- as.data.frame(t(tmp))
  names(tmp) <- c("Success Rate")
  tmp <- slice(tmp, 1:2)
  tmp$`Txn Type` <- row.names(tmp)
  row.names(tmp) <- NULL
  
  plot <-
    hchart(
      object = tmp,
      type = "bar",
      hcaes(x = `Txn Type`, y = `Success Rate`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      )
    )) %>% hc_title(text = "Mandates Vs Non Mandates Success Rate", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                  labels = list(formatter = JS(
                                                                                                                                    "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                  ))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  return(plot)
}

```

```{r mandates_table_volume, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(mandate_vs_normal) > 0 & mandate_vs_normal$mandate_sr > mandate_vs_normal$order_sr) {
  tmp <- mandate_vs_normal
  tmp <- as.data.frame(t(tmp))
  names(tmp) <- c("Volume")
  tmp <- slice(tmp, 3:6)
  tmp$`Txn Type` <- row.names(tmp)
  row.names(tmp) <- NULL
  tmp$`Txn Type`[tmp$`Txn Type` == "t_order_txns"] <- "Non Mandates"
  tmp$`Txn Type`[tmp$`Txn Type` == "t_mandate_txns"] <- "Mandates"

  # t <-
  #   tmp[tmp$`Txn Type` == "" |
  #         tmp$`Txn Type` == "Non Mandates", ]
  # # t$`t_mandate_txns` <- NULL
  # t[t$`Txn Type` == "Mandates" , "t_mandate_txns"] <-
  #   tmp[tmp$`Txn Type` == "t_mandate_txns" , "Volume"]
  # t[t$`Txn Type` == "Non Mandates" , "t_order_txns"] <-
  #   tmp[tmp$`Txn Type` == "t_order_txns" , "Volume"]

  plot <-
    
    hchart(
      object = tmp,
      type = "bar",
      hcaes(x = `Txn Type`, y = `Volume`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y  }")
      )
    )) %>% hc_title(text = "Mandates Vs Non Mandates Volume", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                            labels = list(formatter = JS("function(){ return '<b>' + this.value}"))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>Total Volume: {point.y}</p><p>Successful Volume : </p><p>{point.s_vol}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))

  return(plot)
}

```

```{r mandates_note, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
 if(!is.na(mandate_vs_normal$mandate_sr) && !is.na(mandate_vs_normal$order_sr) && nrow(mandate_vs_normal) > 0 & mandate_vs_normal$mandate_sr > mandate_vs_normal$order_sr){

  mandate_text_note <- text_spec(
    paste(
        "Note:Comparison of Merchant level Mandate Transactions SR to Merchant level Non-Mandate Transactions SR."
    ),
    "html",
    color = "#666F7D",
    font_size = 14,
    extra_css = note_css
  )


}

note <- str_interp('<div class = "text_note" style = "display:block">
${mandate_text_note}
<br><br>
</div>')
cat(note)
#   note <- str_interp('<div class = "text_note">
# ${mandate_text_note}
# <br><br>
# </div>')



```


:::


```{r js_heading, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
funnel_text <- text_spec(paste("JUSPAY SAFE PERFORMANCE"),
                         "html")

note <- str_interp('<div id = "heading">
${funnel_text}
</div>')

if (nrow(otp_summarized > 0)) {
  cat(note)
}

```

```{r otp_funnel, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(otp_summarized > 0)) {
  otp_data <- as.data.frame(t(otp_summarized))
  names(otp_data) <- c("y")
  otp_data$values <- row.names(otp_data)
  otp_data <- otp_data[-1, ]
  row.names(otp_data) <- NULL
  otp_data$y <- as.numeric(otp_data$y)
  otp_data$total <- max(otp_data$y)
  otp_data$total <- as.numeric(otp_data$total)
  otp_data$fraction <- 100 * (round(otp_data$y / otp_data$total, 2))
  otp_data <-
    otp_data %>% drop_na() %>% rename("Steps in a Flow" = values, "Volume for Each Step" = y)
  otp_data$`Steps in a Flow`[otp_data$`Steps in a Flow` == "Volume"] <-
    "Auth Method OTP Volume"
  chart_height <- setChartHeight(nrow(otp_data))
  plot <-
    hchart(
      object = otp_data,
      type = "bar",
      hcaes(x = `Steps in a Flow`, y = `Volume for Each Step`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        useHTML = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        format = '<p> {point.y} ({point.fraction}%)</p>'
      )
    )) %>% hc_title(text = "OTP Flow Funnel") %>%  hc_chart(backgroundColor = '#ffffff', width = 1160) %>% hc_chart(height = chart_height) %>% hc_size(height = 350)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>Value : {point.y}</p><p>Success Rate : </p><p>{point.fraction}%</p>') %>% hc_xAxis(title = list(margin = 15)) %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  return(plot)
}
```


```{r vies_heading, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(vies_table_juspay > 0) && (vies_table_juspay$repeat_sr > vies_table_juspay$threeds_sr)) {
vies_text <- text_spec(paste("VIES Repeat Performance"),
                       "html")

note <- str_interp('<div id = "heading">
${vies_text}
</div>')

cat(note)
}

```


:::{.mr_plots_highchart}
```{r vies_sr, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(vies_table > 0)) {
  t <-
    vies_table %>% select(repeat_sr, threeds_sr) %>% rename("VIES REPEAT" = repeat_sr, "THREE DS" = threeds_sr)
  t <- as.data.frame(t(t))
  names(t) <- c("Success Rate")
  t$Type <- row.names(t)
  row.names(t) <- NULL
  
  plot <-
    hchart(
      object = t,
      type = "bar",
      hcaes(x = Type, y = `Success Rate`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      )
    )) %>% hc_title(text = "VIES Repeat Vs 3DS ", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                       labels = list(formatter = JS(
                                                                                                                         "function(){ return '<b>' + this.value +'%' }"
                                                                                                                       ))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  
  return(plot)
  
}
```

```{r vies_vol, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(vies_table > 0)) {
  t <-
    vies_table %>% select(repeat_txns, threeds_txns) %>% rename("VIES REPEAT" = repeat_txns, "THREE DS" = threeds_txns)
  t <- as.data.frame(t(t))
  names(t) <- c("Volume")
  t$Type <- row.names(t)
  row.names(t) <- NULL
  
  plot <-
    hchart(
      object = t,
      type = "bar",
      hcaes(x = Type, y = Volume),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y }")
      )
    )) %>% hc_title(text = "VIES Repeat Vs 3DS ", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                       labels = list(formatter = JS("function(){ return '<b>' + this.value }"))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  
  return(plot)
  
}
```
:::

```{r vies_sr_juspay, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(vies_table_juspay > 0)) {
  t <-
    vies_table_juspay %>% select(repeat_sr, threeds_sr) %>% rename("Juspay level VIES REPEAT" = repeat_sr, "THREE DS" = threeds_sr)
  t <- as.data.frame(t(t))
  names(t) <- c("Success Rate")
  t$Type <- row.names(t)
  row.names(t) <- NULL
  
  plot <-
    hchart(
      object = t,
      type = "bar",
      hcaes(x = Type, y = `Success Rate`),
      color = "#5C9DB9",
      marginRight = 100
    ) %>% hc_plotOptions(bar = list(
      pointWidth = 34,
      dataLabels = list(
        enabled = T,
        inside = T,
        crop = F,
        color = '#222222',
        style = list(textOutline = 0, fontWeight = 'bold'),
        formatter = JS("function(){ return '<b>' + this.y +'%' }")
      )
    )) %>% hc_title(text = "Juspay level VIES Repeat Vs Merchant 3DS ", margin = 30) %>%  hc_chart(backgroundColor = '#ffffff') %>% hc_yAxis(title = list(margin = 15),
                                                                                                                                             labels = list(formatter = JS(
                                                                                                                                               "function(){ return '<b>' + this.value +'%' }"
                                                                                                                                             ))) %>%  hc_size(width = 1160, height = 250)  %>% hc_tooltip(useHTML = TRUE, pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>%
    hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
  
  return(plot)
  
}
```



```{r enroll, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
# if(nrow(enroll_table) > 1){
# enroll_table <- enroll_table %>% drop_na() %>% arrange(desc(enroll_succ_rate)) %>% rename("Merchant ID" = merchant_id,"Enroll Success Rate" = enroll_succ_rate,"Repeat Success Rate" = repeat_succ_rate)
# plot <- hchart(object = enroll_table, type = "bar", hcaes(x = `Merchant ID`, y = `Enroll Success Rate`), color = "#5C9DB9",marginRight = 100) %>% hc_plotOptions(bar = list(pointWidth = 34,dataLabels = list(enabled = T,inside = T,crop = F,color = '#222222',style = list(textOutline = 0,fontWeight = 'bold'),formatter = JS("function(){ return '<b>' + this.y +'%' }")))) %>% hc_title(text = "VIES Enrollment",margin = 30) %>%  hc_chart(backgroundColor = '#ffffff',width = 1160,height = 400) %>% hc_yAxis(title = list(margin = 15), labels = list(formatter = JS("function(){ return '<b>' + this.value +'%' }"))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE,pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>% 
#   hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
# return(plot)
# }
```

```{r repeat, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
# if(nrow(enroll_table) > 1){
# enroll_table <- enroll_table  %>% arrange(desc(`Enroll Success Rate`))
# plot <- hchart(object = enroll_table, type = "bar", hcaes(x = `Merchant ID`, y = `Repeat Success Rate`), color = "#5C9DB9",marginRight = 100) %>% hc_plotOptions(bar = list(pointWidth = 34,dataLabels = list(enabled = T,inside = T,crop = F,color = '#222222',style = list(textOutline = 0,fontWeight = 'bold'),formatter = JS("function(){ return '<b>' + this.y +'%' }")))) %>% hc_title(text = "VIES Repeat Success Rate",margin = 30) %>%  hc_chart(backgroundColor = '#ffffff',width = 1160,height = 400) %>% hc_yAxis(title = list(margin = 15), labels = list(formatter = JS("function(){ return '<b>' + this.value +'%' }"))) %>% hc_chart(height = 250) %>% hc_size(height = 250)  %>% hc_tooltip(useHTML = TRUE,pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>% 
#   hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
# return(plot)
# }
```

```{r mandate, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
# if(nrow(emandate_sr_table) > 0){
#   emandate_sr_table <- emandate_sr_table  %>% drop_na() %>% arrange(desc(SR))
# plot <- highchart() %>% hc_add_series(data = emandate_sr_table,hcaes(x = merchant, y = SR, group = txn_object_type),type = "bar")  %>% hc_title(text = "Mandate & E-Mandate for Payment & Register") %>% hc_plotOptions(bar = list(pointWidth = 34,dataLabels = list(enabled = T,inside = T,crop = F,color = '#222222',style = list(textOutline = 0,fontWeight = 'bold'),formatter = JS("function(){ return '<b>' + this.y +'%' }")))) %>% hc_title(text = "Mandate Type Success Rate Comparison",margin = 30) %>%  hc_chart(backgroundColor = '#ffffff',width = 1160,marginRight = 100,height = 400) %>% hc_size(height = 400) %>% hc_yAxis(title = list(margin = 15), title = list(text = "Success Rate"),labels = list(formatter = JS("function(){ return '<b>' + this.value +'%' }"))) %>% hc_xAxis( title = list(text = "Merchant Vs Industry"),categories = unique(emandate_sr_table$merchant)) %>% hc_tooltip(useHTML = TRUE,pointFormat = '<p>{point.y}</p>') %>% hc_xAxis(title = list(margin = 15)) %>% 
#   hc_plotOptions(series = list(groupPadding = 0, pointPadding = 0.1))
# return(plot)
# }
```




```{r head_plc, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}


if (any(!is.na(
  c(drop_na(potential_improvemnt_bank_filter),
    drop_na(potential_improvemnt_cards_filter),
    drop_na(potential_improvemnt_nb_filter),
    drop_na(potential_improvemnt_wallets_filter),
    drop_na(potential_improvemnt_upi_filter)
  )
))) {
  cat(glue('<div id = "performace_heading" > <br>
{plc_heading}
</div>'))
  cat(glue('<div id = "heading" >
{explain_plc}
</div>'))
}
```

```{r bank_data_cb_all_plc, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if (nrow(potential_improvemnt_bank_filter) > 0) {
  if (!is.null(potential_improvemnt_bank_filter) > 0) {
    cat(glue('<div id = "subheading">{heading_bank_pg}</div>'))
    # rownames(potential_improvemnt_cards_filter) <- NULL
    potential_improvemnt_bank_filter %>%  drop_na() %>% kbl() %>% kable_material(c("hover"))
  }
}
```

```{r credit_data_cb_all_plc, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if (nrow(potential_improvemnt_cards_filter) > 0) {
  if (!is.null(potential_improvemnt_cards_filter) > 0) {
    cat(glue('<div id = "subheading">{heading_card_pg}</div>'))
    # rownames(potential_improvemnt_cards_filter) <- NULL
    potential_improvemnt_cards_filter %>%  drop_na() %>% kbl() %>% kable_material(c("hover"))
  }
}
```

```{r nb_data_all_plc, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if (nrow(potential_improvemnt_nb_filter) > 0) {
  if (!is.null(potential_improvemnt_nb_filter) > 0) {
    cat(glue('<div id = "subheading">{heading_nb_pg}</div>'))
    rownames(potential_improvemnt_nb_filter) <- NULL
    potential_improvemnt_nb_filter %>%  drop_na() %>% kbl() %>% kable_material(c("hover"))
    # >% column_spec(1, bold = T)
    # %>% rename("Potential Improvement SR" =`Potential Improvement Success Rate`)
  }
}
```

```{r wallet_data_all, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(potential_improvemnt_wallets_filter)>0) {
  if (!is.null(potential_improvemnt_wallets_filter)) {
    cat(glue('<div id = "subheading">{heading_wallet_pg}</div>'))
    rownames(potential_improvemnt_wallets_filter) <- NULL
    potential_improvemnt_wallets_filter %>%  drop_na()  %>% kbl() %>% kable_material(c("hover"))
    # %>% rename("Potential Improvement SR" =`Potential Improvement Success Rate`)
  }
}
```

```{r upi_pay_data_all, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(potential_improvemnt_upi_filter)>0) {
  if (!is.null(potential_improvemnt_upi_filter) > 0) {
    cat(glue('<div id = "subheading">{heading_upi_pay_pg}</div>'))
    rownames(potential_improvemnt_upi_filter) <- NULL
    potential_improvemnt_upi_filter %>%  drop_na()  %>% mutate(`UPI App` = paste('<div class = "UPIIntent">', `UPI App` , '</div>')) %>% kbl(escape = FALSE) %>% kable_material(c("hover"))
    # %>% column_spec(1, bold = T)
  }
}
```


```{r plc_note, comment= NA, message = FALSE,echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(any(!is.null(
  c(
    potential_improvemnt_cards_filter,
    potential_improvemnt_nb_filter,
    potential_improvemnt_wallets_filter,
    potential_improvemnt_upi_filter
  )
))) {
  cat(glue('<div class = "text_note" >
{note_plc}
</div>'))
}
```



```{r blacklist, comment= NA,message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(blacklist) > 0) {
 if (!is.null(blacklist) > 0) {
    cat(glue('<div id = "subheading">{heading_blacklist}</div>'))
    # rownames(blacklist) <- NULL
    cat((blacklist)  %>%  drop_na()  %>% kbl() %>% kable_material(c("hover")))
    cat(glue('<div class = "text_note" >{note_blacklist}</div><br>'))

     # mutate(`UPI App Selected` = paste('<div class = "UPIIntent">', `UPI App Selected` , '</div>')) %>%    # %>% column_spec(1, bold = T)
 }
}

```

```{r verify_vpa, comment= NA,message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(verify_vpa) > 0) {
 if (!is.null(verify_vpa) > 0) {
    cat(glue('<div id = "subheading">{heading_text_validate_vpa}</div>'))
    # rownames(blacklist) <- NULL
    cat((verify_vpa)  %>%  drop_na()  %>% kbl() %>% kable_material(c("hover")))
    cat(glue('<div class = "text_note" >{note_verify_vpa}</div><br>'))

     # mutate(`UPI App Selected` = paste('<div class = "UPIIntent">', `UPI App Selected` , '</div>')) %>%    # %>% column_spec(1, bold = T)
 }
}

```


```{r fallback_pgs, comment= NA,message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(fallback_pgs) > 0) {
 if (!is.null(fallback_pgs) > 0) {
    cat(glue('<div id = "subheading">{heading_fallback}</div>'))
    # rownames(blacklist) <- NULL
    cat((fallback_pgs)  %>%  drop_na()  %>% kbl() %>% kable_material(c("hover")))
    cat(glue('<div class = "text_note" >{note_fallback}</div><br>'))

     # mutate(`UPI App Selected` = paste('<div class = "UPIIntent">', `UPI App Selected` , '</div>')) %>%    # %>% column_spec(1, bold = T)
 }
}

```

<br>
<div id = "subheading">
`r heading_text_value_reord`
</div>

```{r reord, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(reorder_table) > 0) {
if (!is.null(reorder_table) > 0) {
cat((reorder_table)  %>%  drop_na()  %>% kbl() %>% kable_material(c("hover")))
note_reorder <- text_spec(
  reorder_text,
  "html",
  color = "#666F7D",
  font_size = 14,
  extra_css = note_css
)
cat(str_interp('
<div class = "text_note">
${note_reorder}
</div>
'))
}
}
```


```{r vpa_validation, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
# cat(glue('<div id = "heading"> <br> {heading_text_value_vpa}</div>
#          <div id = "underline_title">{vpa_feedback_text}</div>
#          '))

```

```{r fallback_pg, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}

# cat(glue('<div id = "heading">{heading_text_value_fallback}</div>'))
# 
# if(!is.null(card_emi_data)){
#   cat(glue('<div id = "subheading">
#   {heading_text_card_emi}</div>'))
#   cat(card_emi_data %>%  drop_na() %>% arrange(desc(vol)) %>% head(10) %>% 
#     kbl() %>%
#     kable_material(c("hover")))
# }
# #not running
# if(!is.null(card_auth_data)){
#   cat(glue('<div id = "subheading">{heading_text_card_auth}</div>
#          '))
#   cat(card_auth_data %>%  drop_na() %>% arrange(desc(vol)) %>% head(10) %>% 
#     kbl() %>%
#     kable_material(c("hover")))
# }

 
```

<div id = "heading"> <br>
`r heading_text_value_dim_sr`
</div>



```{r dim5p_table, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(dim5p_data)>0) {
  cat(dim5p_data %>% arrange(desc(Volume)) %>% head(10) %>%
        kbl() %>%
        kable_material(c("hover")))
  cat(glue('<div class = "text_note" >{note_dimension_table}</div><br>'))
} else{
  cat(glue('<div class = "text_note" >{note_dimension}</div>'))
}
```



```{r otp_affected, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE, results='asis'}
if(nrow(otp_affected) > 0) {
  cat(str_interp('
<div id = "heading1">
<br>
${heading_text_value_otp}
</div>'))
  
  cat(
    otp_affected %>%
      drop_na() %>%
      select(-MID) %>%
      arrange(desc(Volume)) %>%
      head(10) %>%  kbl() %>%
      kable_material(c("hover"))
  )
}
```    
<div id  = "performace_heading"> <br>
`r heading_text_payments_insights`
</div>
```{r new_final, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(new_final) > 0 ){
    cat(glue('<div id = "subheading">{heading_new_orders}</div>'))
    cat(new_final %>% kbl() %>% kable_material(c("hover")))
}
```


```{r started, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(started) > 0 ){
    cat(glue('<div id = "subheading">{heading_started}</div>'))
    cat(started %>% kbl() %>% kable_material(c("hover")))
}
```
```{r manual_review_volume, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(manual_review_volume) > 0 ){
    cat(glue('<div id = "subheading">{heading_manual_review}</div>'))
    cat(manual_review_volume %>% kbl() %>% kable_material(c("hover")))
}
```

```{r pending_volume, comment= NA, message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
if(nrow(pending_volume) > 0 ){
    cat(glue('<div id = "subheading">{heading_pending_refunds}</div>'))
    cat(pending_volume %>% kbl() %>% kable_material(c("hover")))
}
```
<div id = "performace_heading"> <br>
`r heading_text_industry_Comparison`
</div>
```{r indus_comparision, comment= NA,message = FALSE, echo=FALSE,warning=FALSE,error=FALSE,results='asis'}
cat(glue(' <div id = "heading1">{heading_text_payment_type_wise}</div>'))



if (nrow(card_brand_ind_data) > 0) {
  cat(glue(
    '<div id = "subheading">{heading_text_card_brand_ind}</div>'
  ))
  
  setnames(
    card_brand_ind_data,
    old = c(
      'gateway',
      'payment_type',
      'payment_method',
      'vol',
      'sr',
      'Ind_vol',
      'Ind_SR'
    ),
    new = c(
      'Payment Gateway',
      'Payment Method Type',
      'Payment Method',
      'Volume',
      'Success Rate',
      'Industry Volume',
      'Industry Success Rate'
    )
  )
  cat(
    card_brand_ind_data %>% drop_na() %>% select(-`Industry Volume`) %>%  kbl() %>% kable_material(c("hover"))
  )
  
}

if (nrow(nb_ind_data) > 0) {
  cat(glue('<div id = "subheading">{heading_text_nb_ind}</div>'))
  
  setnames(
    nb_ind_data,
    old = c(
      'gateway',
      'payment_type',
      'payment_method',
      'vol',
      'sr',
      'Ind_vol',
      'Ind_SR'
    ),
    new = c(
      'Payment Gateway',
      'Payment Method Type',
      'Payment Method',
      'Volume',
      'Success Rate',
      'Industry Volume',
      'Industry Success Rate'
    )
  )
  cat(
    nb_ind_data  %>% drop_na()  %>% select(-`Industry Volume`) %>% kbl() %>% kable_material(c("hover"))
  )
  
}

if (nrow(re_wal_ind_data) > 0) {
  cat(glue('<div id = "subheading">{heading_text_re_wal_ind}</div>'))
  
  setnames(
    re_wal_ind_data,
    old = c(
      'gateway',
      'payment_type',
      'payment_method',
      'vol',
      'sr',
      'Ind_vol',
      'Ind_SR'
    ),
    new = c(
      'Payment Gateway',
      'Payment Method Type',
      'Payment Method',
      'Volume',
      'Success Rate',
      'Industry Volume',
      'Industry Success Rate'
    )
  )
  cat(
    re_wal_ind_data  %>% drop_na() %>% select(
      `Payment Gateway`,
      Bank,
      Volume,
      `Success Rate`,
      `Industry Success Rate`
    ) %>%  kbl() %>%  kable_material(c("hover"))
  )
  
}

if (nrow(dir_wal_ind_data) > 0) {
  cat(glue('<div id = "subheading">{heading_text_dir_wal_ind}</div>'))
  setnames(
    dir_wal_ind_data,
    old = c(
      'gateway',
      'payment_type',
      'payment_method',
      'vol',
      'sr',
      'Ind_vol',
      'Ind_SR'
    ),
    new = c(
      'Payment Gateway',
      'Payment Method Type',
      'Payment Method',
      'Volume',
      'Success Rate',
      'Industry Volume',
      'Industry Success Rate'
    )
  )
  cat(
    dir_wal_ind_data %>% drop_na() %>% select(
      `Payment Gateway`,
      Bank,
      Volume,
      `Success Rate`,
      `Industry Success Rate`
    ) %>% kbl() %>% kable_material(c("hover"))
  )
}

if (nrow(upi_pay_ind_data) > 0) {
  cat(glue('<div id = "subheading">{heading_text_upi_pay_ind}</div>'))
  
  
  setnames(
    upi_pay_ind_data,
    old = c('payment_source', 'gateway', 'vol', 'sr', 'Ind_vol', 'Ind_SR'),
    new = c(
      'UPI App Selected',
      'Payment Gateway',
      'Volume',
      'Success Rate',
      'Industry Volume',
      'Industry Success Rate'
    )
  )
  cat(
    upi_pay_ind_data %>% drop_na() %>%  mutate(
      `UPI App Selected` = paste('<div class = "UPIIntent">', `UPI App Selected` , '</div>')
    ) %>% select(
      `Payment Gateway`,
      `UPI App Selected`,
      Volume,
      `Success Rate`,
      `Industry Success Rate`
    ) %>% kbl(escape = FALSE) %>% kable_material(c("hover"))
  )
  # %>% kable_styling(font_size =0)
}

if (nrow(upi_col_ind_data) > 0) {
  cat(glue('<div id = "subheading">{heading_text_upi_col_ind}</div>'))
  
  
  setnames(
    upi_col_ind_data,
    old = c('handle', 'gateway', 'vol', 'sr', 'Ind_vol', 'Ind_SR'),
    new = c(
      'UPI Handle',
      'Payment Gateway',
      'Volume',
      'Success Rate',
      'Industry Volume',
      'Industry Success Rate'
    )
  )
  cat(
    upi_col_ind_data %>% drop_na()  %>% select(
      `Payment Gateway`,
      `UPI Handle`,
      Volume,
      `Success Rate`,
      `Industry Success Rate`
    ) %>% kbl() %>% kable_material(c("hover"))
  )
  
}
note_industry <- text_spec(
  paste(
    "Note: If a Payment Type lacks data, it signifies that your Success Rate's are better when compared to Industry"
  ),
  "html",
  color = "#666F7D",
  font_size = 14,
  extra_css = note_css
)
cat(str_interp('
<div class = "text_note">
${note_industry}
</div>
'))
```



